-- created_at의 값은 도메인(Board)이 생성 시점에 부여합니다(단일 소스).
-- INSERT 시 항상 값이 채워지므로 DB DEFAULT는 두지 않고 NOT NULL 제약만 유지합니다.
CREATE TABLE IF NOT EXISTS board
(
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    content    TEXT         NOT NULL,
    created_at TIMESTAMP    NOT NULL
);
