-- created_at의 값은 도메인(Board)이 생성 시점에 부여합니다(단일 소스).
-- INSERT 시 항상 값이 채워지므로 DB DEFAULT는 두지 않고 NOT NULL 제약만 유지합니다.
CREATE TABLE IF NOT EXISTS board
(
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    content    TEXT         NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    -- 조회수. 조회마다 DB를 때리지 않고 Redis에서 누적한 뒤 주기적으로 여기에 write-back합니다.
    view_count BIGINT       NOT NULL DEFAULT 0
);

-- 이미 board 테이블이 존재하던 DB(초기 버전)에도 view_count가 추가되도록 하는 멱등 마이그레이션.
ALTER TABLE board ADD COLUMN IF NOT EXISTS view_count BIGINT NOT NULL DEFAULT 0;

-- 아카이브 배치의 키셋 조회(WHERE created_at < :before ... ORDER BY id)에서 created_at 범위 필터가
-- 대용량일 때 풀스캔이 되지 않도록 인덱스를 둡니다. 목록 API는 PK(id)만 쓰므로 별도 인덱스가 필요 없습니다.
CREATE INDEX IF NOT EXISTS idx_board_created_at ON board (created_at);

-- 사용자(인증). 로그인 시 자체 발급 JWT의 subject가 되는 id를 채번합니다.
-- password_hash는 BCrypt(60자) + 여유로 VARCHAR(100). role은 'USER'/'ADMIN'(도메인 Role enum과 정합).
CREATE TABLE IF NOT EXISTS users
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMP    NOT NULL
);

-- 게시글 작성자. 기존 board 행(작성자 미상)도 안전하도록 nullable로 추가하며, 신규 생성은 항상 채웁니다.
-- 참조 무결성은 앱 레이어에서 유지합니다(멱등 ALTER로 하드 FK를 얹기 어려워 컬럼 + 인덱스만 둡니다).
ALTER TABLE board ADD COLUMN IF NOT EXISTS author_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_board_author_id ON board (author_id);
