-- created_at의 값은 도메인(Board)이 생성 시점에 부여합니다(단일 소스).
-- INSERT 시 항상 값이 채워지므로 DB DEFAULT는 두지 않고 NOT NULL 제약만 유지합니다.
CREATE TABLE IF NOT EXISTS board
(
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    content    TEXT         NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

-- 아카이브 배치의 키셋 조회(WHERE created_at < :before ... ORDER BY id)에서 created_at 범위 필터가
-- 대용량일 때 풀스캔이 되지 않도록 인덱스를 둡니다. 목록 API는 PK(id)만 쓰므로 별도 인덱스가 필요 없습니다.
CREATE INDEX IF NOT EXISTS idx_board_created_at ON board (created_at);
