apiVersion: v1
kind: Secret
metadata:
  name: search-platform-secrets
  labels:
    app.kubernetes.io/part-of: search-platform
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  SEARCH_JWT_SECRET: {{ .Values.security.jwtSecret | quote }}
  SEARCH_ADMIN_PASSWORD: {{ .Values.security.adminPassword | quote }}
