-- Flyway V1: 초기 스키마. 이전엔 R2dbcSchemaInitializer가 CREATE TABLE IF NOT EXISTS로 멱등 실행했으나,
-- JPA 전환과 함께 Flyway(버전 관리 마이그레이션)로 이관했습니다. 앞으로 스키마 변경은 V2__*.sql로 추가합니다
-- (Flyway가 flyway_schema_history로 적용 이력을 추적하므로 IF NOT EXISTS 같은 방어는 더 이상 필요 없습니다).

-- created_at의 값은 도메인(Board)이 생성 시점에 부여합니다(단일 소스).
-- INSERT 시 항상 값이 채워지므로 DB DEFAULT는 두지 않고 NOT NULL 제약만 유지합니다.
CREATE TABLE board
(
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    content    TEXT         NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    -- 조회수. 조회마다 DB를 때리지 않고 Redis에서 누적한 뒤 주기적으로 여기에 write-back합니다.
    view_count BIGINT       NOT NULL DEFAULT 0,
    -- 게시글 작성자(users.id). 신규 생성은 항상 채우며, 작성자 미상(과거 데이터)은 null 허용.
    -- 참조 무결성은 앱 레이어에서 유지합니다(하드 FK 대신 컬럼 + 인덱스).
    author_id  BIGINT
);

-- 아카이브 배치의 키셋 조회(WHERE created_at < :before ... ORDER BY id)에서 created_at 범위 필터가
-- 대용량일 때 풀스캔이 되지 않도록 인덱스를 둡니다. 목록 API는 PK(id)만 쓰므로 별도 인덱스가 필요 없습니다.
CREATE INDEX idx_board_created_at ON board (created_at);
CREATE INDEX idx_board_author_id ON board (author_id);

-- 사용자(인증). 로그인 시 자체 발급 JWT의 subject가 되는 id를 채번합니다.
-- password_hash는 BCrypt(60자) + 여유로 VARCHAR(100). role은 'USER'/'ADMIN'(도메인 Role enum과 정합).
CREATE TABLE users
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMP    NOT NULL
);

-- Transactional Outbox: 게시글 쓰기와 "같은 트랜잭션"으로 이벤트를 기록해 이중쓰기 문제(DB엔 반영됐는데
-- 메시지는 유실)를 없앱니다. 릴레이가 published_at IS NULL 행을 id 순으로 읽어 Kafka(board-changed)에 발행한 뒤
-- published_at을 찍습니다. 소비자는 event_id로 멱등 처리하므로 at-least-once 재발행이 안전합니다.
-- payload는 직렬화된 BoardChangedEvent(JSON) 원문이며, 릴레이는 이를 그대로 재발행합니다(불투명 바이트).
CREATE TABLE board_outbox
(
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 이벤트 고유 id(소비자 멱등 키). 프로듀서가 부여하며 중복 발행돼도 소비자가 무시할 수 있습니다.
    event_id      VARCHAR(36) NOT NULL UNIQUE,
    -- 대상 게시글 id. 조회/디버깅용.
    aggregate_id  BIGINT      NOT NULL,
    event_type    VARCHAR(20) NOT NULL,
    -- Kafka 메시지 key(= boardId 문자열). 같은 게시글 이벤트의 파티션 순서를 보장합니다.
    partition_key VARCHAR(64) NOT NULL,
    payload       TEXT        NOT NULL,
    created_at    TIMESTAMP   NOT NULL DEFAULT now(),
    -- 발행 완료 시각. NULL이면 미발행(릴레이 대상). 발행 성공 후에만 채워집니다(commit-then-publish).
    published_at  TIMESTAMP
);

-- 릴레이의 미발행 폴링(WHERE published_at IS NULL ORDER BY id)을 위한 부분 인덱스.
-- 발행 완료 행은 인덱스에서 빠져, 미발행분이 적을수록 스캔 비용이 항상 작게 유지됩니다.
CREATE INDEX idx_board_outbox_unpublished ON board_outbox (id) WHERE published_at IS NULL;

-- 리프레시 토큰(회전 + 재사용 감지). access JWT가 만료돼도 이 토큰으로 재발급받습니다.
-- 원문 토큰은 클라이언트에게만 주어지고 서버는 SHA-256 해시(token_hash)만 저장합니다(DB 유출 시에도 원문 복원 불가).
-- 재발급(refresh) 시 사용한 토큰은 revoked_at을 찍어 폐기하고 새 토큰을 발급합니다(1회용). 이미 폐기된 토큰이
-- 다시 제시되면 재사용(탈취 의심)으로 보고 해당 user_id의 모든 토큰을 폐기합니다.
CREATE TABLE refresh_tokens
(
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    -- 원문 토큰의 SHA-256 hex(64자). 조회 키이자 저장값이며, UNIQUE로 중복 발급을 방지합니다.
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP   NOT NULL,
    -- NULL = 활성. 값이 있으면 폐기됨(회전으로 소진되었거나 재사용 감지로 무효화됨).
    revoked_at TIMESTAMP,
    created_at TIMESTAMP   NOT NULL DEFAULT now()
);

-- 재사용 감지 시 특정 사용자의 모든 토큰을 폐기(WHERE user_id = ?)하는 조회를 뒷받침합니다.
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
