-- Flyway V2: 상품(Product) 도메인 추가. 짧은 상품명의 초성/자동완성 검색(Elasticsearch + Nori/ICU)을 위한
-- 정본 테이블과, board와 동일한 Transactional Outbox 파이프라인(product_outbox → Kafka product-changed →
-- search-indexer → products 인덱스)을 위한 아웃박스 테이블을 만든다. board_outbox와 물리적으로 분리해
-- 두 도메인의 릴레이/토픽을 독립적으로 운영한다(board 경로는 무변경).

-- created_at은 도메인(Product)이 생성 시점에 부여합니다(단일 소스) — board와 동일하게 DB DEFAULT 없이 NOT NULL.
CREATE TABLE products
(
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 상품명. 초성/자동완성 검색 대상이며 짧은 문자열이라 board.title과 동일한 VARCHAR(255).
    name       VARCHAR(255) NOT NULL,
    -- 상품 가격(원).
    price      BIGINT       NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

-- 목록/재색인 키셋 순회(ORDER BY id)는 PK로 충분하고, 생성시각 범위 조회 대비로 인덱스를 둡니다(board와 정합).
CREATE INDEX idx_products_created_at ON products (created_at);

-- Transactional Outbox(상품 전용). board_outbox와 동형이며, 릴레이가 published_at IS NULL 행을 id 순으로 읽어
-- Kafka(product-changed)로 발행합니다. payload는 직렬화된 ProductChangedEvent(JSON) 원문입니다.
CREATE TABLE product_outbox
(
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      VARCHAR(36) NOT NULL UNIQUE,
    aggregate_id  BIGINT      NOT NULL,
    event_type    VARCHAR(20) NOT NULL,
    -- Kafka 메시지 key(= productId 문자열). 같은 상품 이벤트의 파티션 순서를 보장합니다.
    partition_key VARCHAR(64) NOT NULL,
    payload       TEXT        NOT NULL,
    created_at    TIMESTAMP   NOT NULL DEFAULT now(),
    published_at  TIMESTAMP
);

-- 릴레이의 미발행 폴링(WHERE published_at IS NULL ORDER BY id)을 위한 부분 인덱스(board_outbox와 동일 패턴).
CREATE INDEX idx_product_outbox_unpublished ON product_outbox (id) WHERE published_at IS NULL;
