-- created_at의 값은 도메인(Board)이 생성 시점에 부여합니다(단일 소스).
-- INSERT 시 항상 값이 채워지므로 DB DEFAULT는 두지 않고 NOT NULL 제약만 유지합니다.
CREATE TABLE IF NOT EXISTS board
(
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    content    TEXT         NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    -- 조회수. 조회마다 DB를 때리지 않고 Redis에서 누적한 뒤 주기적으로 여기에 write-back합니다.
    view_count BIGINT       NOT NULL DEFAULT 0
);

-- 이미 board 테이블이 존재하던 DB(초기 버전)에도 view_count가 추가되도록 하는 멱등 마이그레이션.
ALTER TABLE board ADD COLUMN IF NOT EXISTS view_count BIGINT NOT NULL DEFAULT 0;

-- 아카이브 배치의 키셋 조회(WHERE created_at < :before ... ORDER BY id)에서 created_at 범위 필터가
-- 대용량일 때 풀스캔이 되지 않도록 인덱스를 둡니다. 목록 API는 PK(id)만 쓰므로 별도 인덱스가 필요 없습니다.
CREATE INDEX IF NOT EXISTS idx_board_created_at ON board (created_at);

-- 사용자(인증). 로그인 시 자체 발급 JWT의 subject가 되는 id를 채번합니다.
-- password_hash는 BCrypt(60자) + 여유로 VARCHAR(100). role은 'USER'/'ADMIN'(도메인 Role enum과 정합).
CREATE TABLE IF NOT EXISTS users
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMP    NOT NULL
);

-- 게시글 작성자. 기존 board 행(작성자 미상)도 안전하도록 nullable로 추가하며, 신규 생성은 항상 채웁니다.
-- 참조 무결성은 앱 레이어에서 유지합니다(멱등 ALTER로 하드 FK를 얹기 어려워 컬럼 + 인덱스만 둡니다).
ALTER TABLE board ADD COLUMN IF NOT EXISTS author_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_board_author_id ON board (author_id);

-- Transactional Outbox: 게시글 쓰기와 "같은 트랜잭션"으로 이벤트를 기록해 이중쓰기 문제(DB엔 반영됐는데
-- 메시지는 유실)를 없앱니다. 릴레이가 published_at IS NULL 행을 id 순으로 읽어 Kafka(board-changed)에 발행한 뒤
-- published_at을 찍습니다. 소비자는 event_id로 멱등 처리하므로 at-least-once 재발행이 안전합니다.
-- payload는 직렬화된 BoardChangedEvent(JSON) 원문이며, 릴레이는 이를 그대로 재발행합니다(불투명 바이트).
CREATE TABLE IF NOT EXISTS board_outbox
(
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 이벤트 고유 id(소비자 멱등 키). 프로듀서가 부여하며 중복 발행돼도 소비자가 무시할 수 있습니다.
    event_id      VARCHAR(36) NOT NULL UNIQUE,
    -- 대상 게시글 id. 조회/디버깅용.
    aggregate_id  BIGINT      NOT NULL,
    event_type    VARCHAR(20) NOT NULL,
    -- Kafka 메시지 key(= boardId 문자열). 같은 게시글 이벤트의 파티션 순서를 보장합니다.
    partition_key VARCHAR(64) NOT NULL,
    payload       TEXT        NOT NULL,
    created_at    TIMESTAMP   NOT NULL DEFAULT now(),
    -- 발행 완료 시각. NULL이면 미발행(릴레이 대상). 발행 성공 후에만 채워집니다(commit-then-publish).
    published_at  TIMESTAMP
);

-- 릴레이의 미발행 폴링(WHERE published_at IS NULL ORDER BY id)을 위한 부분 인덱스.
-- 발행 완료 행은 인덱스에서 빠져, 미발행분이 적을수록 스캔 비용이 항상 작게 유지됩니다.
CREATE INDEX IF NOT EXISTS idx_board_outbox_unpublished ON board_outbox (id) WHERE published_at IS NULL;
